
# Scenario 1 -> install nginx only in debian os and distribution major 18 
- name: Install Nginx on Ubuntu 18.04
  apt: 
    name: nginx=1.18.0
    state: present 
  when: ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution_major_version'] == '18'

# Scenario 2 -> configuration based o the environment
- name: Deploy configuraiton files
    template: 
      src: "{{app_env}}_config.j2"
      dest: "/etc/myapp/config.conf"
  vars:
    app_env: production

# Scenario 3 -> install all packages in all servers, but only start the production servers
- name: Install required packages
    apt: 
    name:
      - package1
      - package2
    state: present 

- name: Start web application service 
    service: 
      name: myapp 
      state: started 
    when: environment == 'production'


